const SET_POKEMONS = 'SET_POKEMONS';
const SET_FAVORITES = 'SET_FAVORITES';
const SET_LOADING = 'SET_LOADING';
const SORT_FAVORITES = 'SORT_FAVORITES';

export { SET_POKEMONS, SET_FAVORITES, SET_LOADING, SORT_FAVORITES };


